<?php
/**
 * ResponseWrapperSolanaTokenSecurityTransferFee
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoPlus Security API Document
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ResponseWrapperSolanaTokenSecurityTransferFee Class Doc Comment
 *
 * @category Class
 * @description Configuration information for transfer fees.(Notice: \&quot;Scheduled Fee\&quot; would take effect and turn into \&quot;Current Fee\&quot; when the epoch is reached.)
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseWrapperSolanaTokenSecurityTransferFee implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ResponseWrapperSolanaTokenSecurity_transfer_fee';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'scheduled_fee_rate' => '\Swagger\Client\Model\ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate[]',
        'current_fee_rate' => '\Swagger\Client\Model\ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'scheduled_fee_rate' => null,
        'current_fee_rate' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'scheduled_fee_rate' => 'scheduled_fee_rate',
        'current_fee_rate' => 'current_fee_rate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'scheduled_fee_rate' => 'setScheduledFeeRate',
        'current_fee_rate' => 'setCurrentFeeRate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'scheduled_fee_rate' => 'getScheduledFeeRate',
        'current_fee_rate' => 'getCurrentFeeRate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['scheduled_fee_rate'] = isset($data['scheduled_fee_rate']) ? $data['scheduled_fee_rate'] : null;
        $this->container['current_fee_rate'] = isset($data['current_fee_rate']) ? $data['current_fee_rate'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets scheduled_fee_rate
     *
     * @return \Swagger\Client\Model\ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate[]
     */
    public function getScheduledFeeRate()
    {
        return $this->container['scheduled_fee_rate'];
    }

    /**
     * Sets scheduled_fee_rate
     *
     * @param \Swagger\Client\Model\ResponseWrapperSolanaTokenSecurityTransferFeeScheduledFeeRate[] $scheduled_fee_rate Scheduled changes to transfer fee rates.
     *
     * @return $this
     */
    public function setScheduledFeeRate($scheduled_fee_rate)
    {
        $this->container['scheduled_fee_rate'] = $scheduled_fee_rate;

        return $this;
    }

    /**
     * Gets current_fee_rate
     *
     * @return \Swagger\Client\Model\ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate
     */
    public function getCurrentFeeRate()
    {
        return $this->container['current_fee_rate'];
    }

    /**
     * Sets current_fee_rate
     *
     * @param \Swagger\Client\Model\ResponseWrapperSolanaTokenSecurityTransferFeeCurrentFeeRate $current_fee_rate current_fee_rate
     *
     * @return $this
     */
    public function setCurrentFeeRate($current_fee_rate)
    {
        $this->container['current_fee_rate'] = $current_fee_rate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
