<?php
/**
 * ResponseWrapperGetScanResultResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoPlus Security API Document
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ResponseWrapperGetScanResultResult Class Doc Comment
 *
 * @category Class
 * @description Response result
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseWrapperGetScanResultResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ResponseWrapperGetScanResult_result';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'chain_id' => 'string',
        'approval_risk' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultApprovalRisk',
        'token_attention' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention',
        'nft_attention' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention',
        'stablecoin_depeg' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultStablecoinDepeg',
        'address_poisoned' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned',
        'excessive_gas_fee' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned',
        'nft_risk' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention',
        'nft_stolen' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned',
        'scan_time' => 'string',
        'request_id' => 'string',
        'token_risk' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention',
        'risky_address_interaction' => '\Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'chain_id' => null,
        'approval_risk' => null,
        'token_attention' => null,
        'nft_attention' => null,
        'stablecoin_depeg' => null,
        'address_poisoned' => null,
        'excessive_gas_fee' => null,
        'nft_risk' => null,
        'nft_stolen' => null,
        'scan_time' => null,
        'request_id' => null,
        'token_risk' => null,
        'risky_address_interaction' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'chain_id' => 'chain_id',
        'approval_risk' => 'approval_risk',
        'token_attention' => 'token_attention',
        'nft_attention' => 'nft_attention',
        'stablecoin_depeg' => 'stablecoin_depeg',
        'address_poisoned' => 'address_poisoned',
        'excessive_gas_fee' => 'excessive_gas_fee',
        'nft_risk' => 'nft_risk',
        'nft_stolen' => 'nft_stolen',
        'scan_time' => 'scan_time',
        'request_id' => 'request_id',
        'token_risk' => 'token_risk',
        'risky_address_interaction' => 'risky_address_interaction'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'chain_id' => 'setChainId',
        'approval_risk' => 'setApprovalRisk',
        'token_attention' => 'setTokenAttention',
        'nft_attention' => 'setNftAttention',
        'stablecoin_depeg' => 'setStablecoinDepeg',
        'address_poisoned' => 'setAddressPoisoned',
        'excessive_gas_fee' => 'setExcessiveGasFee',
        'nft_risk' => 'setNftRisk',
        'nft_stolen' => 'setNftStolen',
        'scan_time' => 'setScanTime',
        'request_id' => 'setRequestId',
        'token_risk' => 'setTokenRisk',
        'risky_address_interaction' => 'setRiskyAddressInteraction'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'chain_id' => 'getChainId',
        'approval_risk' => 'getApprovalRisk',
        'token_attention' => 'getTokenAttention',
        'nft_attention' => 'getNftAttention',
        'stablecoin_depeg' => 'getStablecoinDepeg',
        'address_poisoned' => 'getAddressPoisoned',
        'excessive_gas_fee' => 'getExcessiveGasFee',
        'nft_risk' => 'getNftRisk',
        'nft_stolen' => 'getNftStolen',
        'scan_time' => 'getScanTime',
        'request_id' => 'getRequestId',
        'token_risk' => 'getTokenRisk',
        'risky_address_interaction' => 'getRiskyAddressInteraction'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['chain_id'] = isset($data['chain_id']) ? $data['chain_id'] : null;
        $this->container['approval_risk'] = isset($data['approval_risk']) ? $data['approval_risk'] : null;
        $this->container['token_attention'] = isset($data['token_attention']) ? $data['token_attention'] : null;
        $this->container['nft_attention'] = isset($data['nft_attention']) ? $data['nft_attention'] : null;
        $this->container['stablecoin_depeg'] = isset($data['stablecoin_depeg']) ? $data['stablecoin_depeg'] : null;
        $this->container['address_poisoned'] = isset($data['address_poisoned']) ? $data['address_poisoned'] : null;
        $this->container['excessive_gas_fee'] = isset($data['excessive_gas_fee']) ? $data['excessive_gas_fee'] : null;
        $this->container['nft_risk'] = isset($data['nft_risk']) ? $data['nft_risk'] : null;
        $this->container['nft_stolen'] = isset($data['nft_stolen']) ? $data['nft_stolen'] : null;
        $this->container['scan_time'] = isset($data['scan_time']) ? $data['scan_time'] : null;
        $this->container['request_id'] = isset($data['request_id']) ? $data['request_id'] : null;
        $this->container['token_risk'] = isset($data['token_risk']) ? $data['token_risk'] : null;
        $this->container['risky_address_interaction'] = isset($data['risky_address_interaction']) ? $data['risky_address_interaction'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets chain_id
     *
     * @return string
     */
    public function getChainId()
    {
        return $this->container['chain_id'];
    }

    /**
     * Sets chain_id
     *
     * @param string $chain_id Chain ID
     *
     * @return $this
     */
    public function setChainId($chain_id)
    {
        $this->container['chain_id'] = $chain_id;

        return $this;
    }

    /**
     * Gets approval_risk
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultApprovalRisk
     */
    public function getApprovalRisk()
    {
        return $this->container['approval_risk'];
    }

    /**
     * Sets approval_risk
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultApprovalRisk $approval_risk approval_risk
     *
     * @return $this
     */
    public function setApprovalRisk($approval_risk)
    {
        $this->container['approval_risk'] = $approval_risk;

        return $this;
    }

    /**
     * Gets token_attention
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention
     */
    public function getTokenAttention()
    {
        return $this->container['token_attention'];
    }

    /**
     * Sets token_attention
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention $token_attention token_attention
     *
     * @return $this
     */
    public function setTokenAttention($token_attention)
    {
        $this->container['token_attention'] = $token_attention;

        return $this;
    }

    /**
     * Gets nft_attention
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention
     */
    public function getNftAttention()
    {
        return $this->container['nft_attention'];
    }

    /**
     * Sets nft_attention
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention $nft_attention nft_attention
     *
     * @return $this
     */
    public function setNftAttention($nft_attention)
    {
        $this->container['nft_attention'] = $nft_attention;

        return $this;
    }

    /**
     * Gets stablecoin_depeg
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultStablecoinDepeg
     */
    public function getStablecoinDepeg()
    {
        return $this->container['stablecoin_depeg'];
    }

    /**
     * Sets stablecoin_depeg
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultStablecoinDepeg $stablecoin_depeg stablecoin_depeg
     *
     * @return $this
     */
    public function setStablecoinDepeg($stablecoin_depeg)
    {
        $this->container['stablecoin_depeg'] = $stablecoin_depeg;

        return $this;
    }

    /**
     * Gets address_poisoned
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned
     */
    public function getAddressPoisoned()
    {
        return $this->container['address_poisoned'];
    }

    /**
     * Sets address_poisoned
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned $address_poisoned address_poisoned
     *
     * @return $this
     */
    public function setAddressPoisoned($address_poisoned)
    {
        $this->container['address_poisoned'] = $address_poisoned;

        return $this;
    }

    /**
     * Gets excessive_gas_fee
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned
     */
    public function getExcessiveGasFee()
    {
        return $this->container['excessive_gas_fee'];
    }

    /**
     * Sets excessive_gas_fee
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned $excessive_gas_fee excessive_gas_fee
     *
     * @return $this
     */
    public function setExcessiveGasFee($excessive_gas_fee)
    {
        $this->container['excessive_gas_fee'] = $excessive_gas_fee;

        return $this;
    }

    /**
     * Gets nft_risk
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention
     */
    public function getNftRisk()
    {
        return $this->container['nft_risk'];
    }

    /**
     * Sets nft_risk
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention $nft_risk nft_risk
     *
     * @return $this
     */
    public function setNftRisk($nft_risk)
    {
        $this->container['nft_risk'] = $nft_risk;

        return $this;
    }

    /**
     * Gets nft_stolen
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned
     */
    public function getNftStolen()
    {
        return $this->container['nft_stolen'];
    }

    /**
     * Sets nft_stolen
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned $nft_stolen nft_stolen
     *
     * @return $this
     */
    public function setNftStolen($nft_stolen)
    {
        $this->container['nft_stolen'] = $nft_stolen;

        return $this;
    }

    /**
     * Gets scan_time
     *
     * @return string
     */
    public function getScanTime()
    {
        return $this->container['scan_time'];
    }

    /**
     * Sets scan_time
     *
     * @param string $scan_time Scan initiation time. UTC+0.
     *
     * @return $this
     */
    public function setScanTime($scan_time)
    {
        $this->container['scan_time'] = $scan_time;

        return $this;
    }

    /**
     * Gets request_id
     *
     * @return string
     */
    public function getRequestId()
    {
        return $this->container['request_id'];
    }

    /**
     * Sets request_id
     *
     * @param string $request_id Request ID
     *
     * @return $this
     */
    public function setRequestId($request_id)
    {
        $this->container['request_id'] = $request_id;

        return $this;
    }

    /**
     * Gets token_risk
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention
     */
    public function getTokenRisk()
    {
        return $this->container['token_risk'];
    }

    /**
     * Sets token_risk
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultTokenAttention $token_risk token_risk
     *
     * @return $this
     */
    public function setTokenRisk($token_risk)
    {
        $this->container['token_risk'] = $token_risk;

        return $this;
    }

    /**
     * Gets risky_address_interaction
     *
     * @return \Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned
     */
    public function getRiskyAddressInteraction()
    {
        return $this->container['risky_address_interaction'];
    }

    /**
     * Sets risky_address_interaction
     *
     * @param \Swagger\Client\Model\ResponseWrapperGetScanResultResultAddressPoisoned $risky_address_interaction risky_address_interaction
     *
     * @return $this
     */
    public function setRiskyAddressInteraction($risky_address_interaction)
    {
        $this->container['risky_address_interaction'] = $risky_address_interaction;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
