<?php
/**
 * ResponseWrapperTokenSecurityB20TokenB20Info
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoPlus Security API Document
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ResponseWrapperTokenSecurityB20TokenB20Info Class Doc Comment
 *
 * @category Class
 * @description It describes the detailed B20 token permission information.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseWrapperTokenSecurityB20TokenB20Info implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ResponseWrapperTokenSecurity_b20_token_b20_info';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'transfer_pausable' => '\Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable',
        'owner_change_balance' => '\Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance',
        'cannot_buy' => '\Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy',
        'metadata_modifiable' => '\Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable',
        'blacklist' => '\Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist',
        'cannot_sell' => '\Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell',
        'whitelist' => '\Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist',
        'mintable' => '\Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoMintable'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'transfer_pausable' => null,
        'owner_change_balance' => null,
        'cannot_buy' => null,
        'metadata_modifiable' => null,
        'blacklist' => null,
        'cannot_sell' => null,
        'whitelist' => null,
        'mintable' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transfer_pausable' => 'transfer_pausable',
        'owner_change_balance' => 'owner_change_balance',
        'cannot_buy' => 'cannot_buy',
        'metadata_modifiable' => 'metadata_modifiable',
        'blacklist' => 'blacklist',
        'cannot_sell' => 'cannot_sell',
        'whitelist' => 'whitelist',
        'mintable' => 'mintable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transfer_pausable' => 'setTransferPausable',
        'owner_change_balance' => 'setOwnerChangeBalance',
        'cannot_buy' => 'setCannotBuy',
        'metadata_modifiable' => 'setMetadataModifiable',
        'blacklist' => 'setBlacklist',
        'cannot_sell' => 'setCannotSell',
        'whitelist' => 'setWhitelist',
        'mintable' => 'setMintable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transfer_pausable' => 'getTransferPausable',
        'owner_change_balance' => 'getOwnerChangeBalance',
        'cannot_buy' => 'getCannotBuy',
        'metadata_modifiable' => 'getMetadataModifiable',
        'blacklist' => 'getBlacklist',
        'cannot_sell' => 'getCannotSell',
        'whitelist' => 'getWhitelist',
        'mintable' => 'getMintable'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['transfer_pausable'] = isset($data['transfer_pausable']) ? $data['transfer_pausable'] : null;
        $this->container['owner_change_balance'] = isset($data['owner_change_balance']) ? $data['owner_change_balance'] : null;
        $this->container['cannot_buy'] = isset($data['cannot_buy']) ? $data['cannot_buy'] : null;
        $this->container['metadata_modifiable'] = isset($data['metadata_modifiable']) ? $data['metadata_modifiable'] : null;
        $this->container['blacklist'] = isset($data['blacklist']) ? $data['blacklist'] : null;
        $this->container['cannot_sell'] = isset($data['cannot_sell']) ? $data['cannot_sell'] : null;
        $this->container['whitelist'] = isset($data['whitelist']) ? $data['whitelist'] : null;
        $this->container['mintable'] = isset($data['mintable']) ? $data['mintable'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transfer_pausable
     *
     * @return \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable
     */
    public function getTransferPausable()
    {
        return $this->container['transfer_pausable'];
    }

    /**
     * Sets transfer_pausable
     *
     * @param \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoTransferPausable $transfer_pausable transfer_pausable
     *
     * @return $this
     */
    public function setTransferPausable($transfer_pausable)
    {
        $this->container['transfer_pausable'] = $transfer_pausable;

        return $this;
    }

    /**
     * Gets owner_change_balance
     *
     * @return \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance
     */
    public function getOwnerChangeBalance()
    {
        return $this->container['owner_change_balance'];
    }

    /**
     * Sets owner_change_balance
     *
     * @param \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoOwnerChangeBalance $owner_change_balance owner_change_balance
     *
     * @return $this
     */
    public function setOwnerChangeBalance($owner_change_balance)
    {
        $this->container['owner_change_balance'] = $owner_change_balance;

        return $this;
    }

    /**
     * Gets cannot_buy
     *
     * @return \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy
     */
    public function getCannotBuy()
    {
        return $this->container['cannot_buy'];
    }

    /**
     * Sets cannot_buy
     *
     * @param \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoCannotBuy $cannot_buy cannot_buy
     *
     * @return $this
     */
    public function setCannotBuy($cannot_buy)
    {
        $this->container['cannot_buy'] = $cannot_buy;

        return $this;
    }

    /**
     * Gets metadata_modifiable
     *
     * @return \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable
     */
    public function getMetadataModifiable()
    {
        return $this->container['metadata_modifiable'];
    }

    /**
     * Sets metadata_modifiable
     *
     * @param \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoMetadataModifiable $metadata_modifiable metadata_modifiable
     *
     * @return $this
     */
    public function setMetadataModifiable($metadata_modifiable)
    {
        $this->container['metadata_modifiable'] = $metadata_modifiable;

        return $this;
    }

    /**
     * Gets blacklist
     *
     * @return \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist
     */
    public function getBlacklist()
    {
        return $this->container['blacklist'];
    }

    /**
     * Sets blacklist
     *
     * @param \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoBlacklist $blacklist blacklist
     *
     * @return $this
     */
    public function setBlacklist($blacklist)
    {
        $this->container['blacklist'] = $blacklist;

        return $this;
    }

    /**
     * Gets cannot_sell
     *
     * @return \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell
     */
    public function getCannotSell()
    {
        return $this->container['cannot_sell'];
    }

    /**
     * Sets cannot_sell
     *
     * @param \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoCannotSell $cannot_sell cannot_sell
     *
     * @return $this
     */
    public function setCannotSell($cannot_sell)
    {
        $this->container['cannot_sell'] = $cannot_sell;

        return $this;
    }

    /**
     * Gets whitelist
     *
     * @return \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist
     */
    public function getWhitelist()
    {
        return $this->container['whitelist'];
    }

    /**
     * Sets whitelist
     *
     * @param \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoWhitelist $whitelist whitelist
     *
     * @return $this
     */
    public function setWhitelist($whitelist)
    {
        $this->container['whitelist'] = $whitelist;

        return $this;
    }

    /**
     * Gets mintable
     *
     * @return \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoMintable
     */
    public function getMintable()
    {
        return $this->container['mintable'];
    }

    /**
     * Sets mintable
     *
     * @param \Swagger\Client\Model\ResponseWrapperTokenSecurityB20TokenB20InfoMintable $mintable mintable
     *
     * @return $this
     */
    public function setMintable($mintable)
    {
        $this->container['mintable'] = $mintable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
