<?php
/**
 * SolanaTxSolChange
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GoPlus Security API Document
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SolanaTxSolChange Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SolanaTxSolChange implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SolanaTxSolChange';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'address' => 'string',
        'post_lamports' => 'string',
        'lamport_changes' => 'string',
        'risky_address' => 'int',
        'from_address' => 'int',
        'pre_lamports' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'address' => null,
        'post_lamports' => null,
        'lamport_changes' => null,
        'risky_address' => 'int32',
        'from_address' => 'int32',
        'pre_lamports' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address' => 'address',
        'post_lamports' => 'post_lamports',
        'lamport_changes' => 'lamport_changes',
        'risky_address' => 'risky_address',
        'from_address' => 'from_address',
        'pre_lamports' => 'pre_lamports'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address' => 'setAddress',
        'post_lamports' => 'setPostLamports',
        'lamport_changes' => 'setLamportChanges',
        'risky_address' => 'setRiskyAddress',
        'from_address' => 'setFromAddress',
        'pre_lamports' => 'setPreLamports'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address' => 'getAddress',
        'post_lamports' => 'getPostLamports',
        'lamport_changes' => 'getLamportChanges',
        'risky_address' => 'getRiskyAddress',
        'from_address' => 'getFromAddress',
        'pre_lamports' => 'getPreLamports'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['post_lamports'] = isset($data['post_lamports']) ? $data['post_lamports'] : null;
        $this->container['lamport_changes'] = isset($data['lamport_changes']) ? $data['lamport_changes'] : null;
        $this->container['risky_address'] = isset($data['risky_address']) ? $data['risky_address'] : null;
        $this->container['from_address'] = isset($data['from_address']) ? $data['from_address'] : null;
        $this->container['pre_lamports'] = isset($data['pre_lamports']) ? $data['pre_lamports'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets post_lamports
     *
     * @return string
     */
    public function getPostLamports()
    {
        return $this->container['post_lamports'];
    }

    /**
     * Sets post_lamports
     *
     * @param string $post_lamports post_lamports
     *
     * @return $this
     */
    public function setPostLamports($post_lamports)
    {
        $this->container['post_lamports'] = $post_lamports;

        return $this;
    }

    /**
     * Gets lamport_changes
     *
     * @return string
     */
    public function getLamportChanges()
    {
        return $this->container['lamport_changes'];
    }

    /**
     * Sets lamport_changes
     *
     * @param string $lamport_changes lamport_changes
     *
     * @return $this
     */
    public function setLamportChanges($lamport_changes)
    {
        $this->container['lamport_changes'] = $lamport_changes;

        return $this;
    }

    /**
     * Gets risky_address
     *
     * @return int
     */
    public function getRiskyAddress()
    {
        return $this->container['risky_address'];
    }

    /**
     * Sets risky_address
     *
     * @param int $risky_address risky_address
     *
     * @return $this
     */
    public function setRiskyAddress($risky_address)
    {
        $this->container['risky_address'] = $risky_address;

        return $this;
    }

    /**
     * Gets from_address
     *
     * @return int
     */
    public function getFromAddress()
    {
        return $this->container['from_address'];
    }

    /**
     * Sets from_address
     *
     * @param int $from_address from_address
     *
     * @return $this
     */
    public function setFromAddress($from_address)
    {
        $this->container['from_address'] = $from_address;

        return $this;
    }

    /**
     * Gets pre_lamports
     *
     * @return string
     */
    public function getPreLamports()
    {
        return $this->container['pre_lamports'];
    }

    /**
     * Sets pre_lamports
     *
     * @param string $pre_lamports pre_lamports
     *
     * @return $this
     */
    public function setPreLamports($pre_lamports)
    {
        $this->container['pre_lamports'] = $pre_lamports;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
